package az.simplexs.simplexs.controller;
import java.math.BigDecimal;import java.time.LocalDate;import java.util.Map;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.stereotype.Controller;import org.springframework.ui.Model;import org.springframework.web.bind.annotation.*;import org.springframework.web.servlet.mvc.support.RedirectAttributes;import az.simplexs.simplexs.repository.qiymet.QiymetRepository;import az.simplexs.simplexs.repository.xidmet.XidmetRepository;
@Controller public class QiymetController{
 private final QiymetRepository repo;private final XidmetRepository xidmetRepo;public QiymetController(QiymetRepository r,XidmetRepository x){repo=r;xidmetRepo=x;}
 @GetMapping("/xidmetQiymetleri") public String list(@RequestParam(required=false)Long basliqId,Model m){var basliqlar=repo.basliqlar();if(basliqId==null&&!basliqlar.isEmpty())basliqId=basliqlar.getFirst().id();m.addAttribute("pageTitle","Xidmət qiymətləri");m.addAttribute("activeMenuGroup","adminPanel");m.addAttribute("activeMenu","xidmetQiymetleri");m.addAttribute("basliqlar",basliqlar);m.addAttribute("qruplar",repo.qruplar(basliqId));m.addAttribute("selectedBasliqId",basliqId);return "pages/xidmetQiymetleri";}
 @GetMapping("/xidmetQiymetleri/qrup/{qrupId}") public String tarifler(@PathVariable Long qrupId,@RequestParam(required=false)Long xidmetQrupuId,@RequestParam(required=false)String q,@RequestParam(required=false)String qiymetStatus,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="100")int size,Model m){var qrup=repo.qruplar(null).stream().filter(x->x.id().equals(qrupId)).findFirst().orElseThrow();size=Math.max(20,Math.min(size,100));long total=repo.xidmetSayi(qrupId,xidmetQrupuId,q,qiymetStatus);int totalPages=Math.max(1,(int)Math.ceil((double)total/size));page=Math.max(1,Math.min(page,totalPages));m.addAttribute("pageTitle",qrup.ad());m.addAttribute("activeMenuGroup","adminPanel");m.addAttribute("activeMenu","xidmetQiymetleri");m.addAttribute("qrup",qrup);m.addAttribute("xidmetQruplari",xidmetRepo.qruplar());m.addAttribute("xidmetler",repo.xidmetler(qrupId,xidmetQrupuId,q,qiymetStatus,size,(page-1)*size));m.addAttribute("selectedXidmetQrupuId",xidmetQrupuId);m.addAttribute("q",q);m.addAttribute("qiymetStatus",qiymetStatus);m.addAttribute("totalCount",total);m.addAttribute("totalPages",totalPages);m.addAttribute("currentPage",page);m.addAttribute("pageSize",size);return "pages/xidmetQiymetTarifleri";}
 @PostMapping("/xidmetQiymetleri/basliq/yeni") public String basliqYarat(@RequestParam String ad,RedirectAttributes a){flash(repo.basliqYarat(ad),a,"Qiymət başlığı yaradıldı.");return redirect(null,null);}
 @PostMapping("/xidmetQiymetleri/basliq/yenile") public String basliqYenile(@RequestParam Long id,@RequestParam String ad,@RequestParam(required=false)String aciqlama,@RequestParam Integer siraNo,@RequestParam(defaultValue="false")boolean aktiv,RedirectAttributes a){flash(repo.basliqYenile(id,ad,aciqlama,siraNo,aktiv),a,"Qiymət başlığı yeniləndi.");return redirect(id,null);}
 @PostMapping("/xidmetQiymetleri/qrup/yeni") public String qrupYarat(@RequestParam Long basliqId,@RequestParam String ad,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate baslamaTarixi,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate bitmeTarixi,@RequestParam(required=false)String aciqlama,@RequestParam Integer siraNo,@RequestParam(required=false)Long klonQrupId,RedirectAttributes a){flash(repo.qrupYarat(basliqId,ad,baslamaTarixi,bitmeTarixi,aciqlama,siraNo,klonQrupId),a,"Qiymət qrupu yaradıldı.");return redirect(basliqId,null);}
 @PostMapping("/xidmetQiymetleri/qrup/yenile") public String qrupYenile(@RequestParam Long id,@RequestParam Long basliqId,@RequestParam String ad,@RequestParam(required=false)String aciqlama,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate baslamaTarixi,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate bitmeTarixi,@RequestParam Integer siraNo,@RequestParam(defaultValue="false")boolean aktiv,RedirectAttributes a){flash(repo.qrupYenile(id,basliqId,ad,aciqlama,baslamaTarixi,bitmeTarixi,siraNo,aktiv),a,"Qiymət qrupu yeniləndi.");return redirect(basliqId,id);}
 @PostMapping("/xidmetQiymetleri/qiymet") public String qiymet(@RequestParam Long qrupId,@RequestParam Long xidmetId,@RequestParam BigDecimal qiymet,@RequestParam(required=false)BigDecimal xestePayFaizi,@RequestParam(required=false)BigDecimal xesteEndirimFaizi,@RequestParam(required=false)BigDecimal qurumEndirimFaizi,@RequestParam(defaultValue="false")boolean edvAktivdir,RedirectAttributes a){flash(repo.qiymetSaxla(qrupId,xidmetId,qiymet,xestePayFaizi,xesteEndirimFaizi,qurumEndirimFaizi,edvAktivdir),a,"Xidmət qiyməti yadda saxlanıldı.");return "redirect:/xidmetQiymetleri/qrup/"+qrupId;}
 @PostMapping("/xidmetQiymetleri/qiymetler") public String qiymetler(@RequestParam Long qrupId,@RequestParam String qiymetlerJson,RedirectAttributes a){if(qiymetlerJson.length()>1_000_000||!qiymetlerJson.trim().startsWith("[")){a.addFlashAttribute("errorMessage","Göndərilən qiymət məlumatları düzgün deyil.");}else{flash(repo.qiymetleriSaxla(qrupId,qiymetlerJson),a,"Dəyişdirilmiş xidmət qiymətləri yadda saxlanıldı.");}return "redirect:/xidmetQiymetleri/qrup/"+qrupId;}
 private void flash(Map<String,Object>r,RedirectAttributes a,String f){String s=String.valueOf(r.getOrDefault("status_kodu",""));a.addFlashAttribute(s.toUpperCase().contains("UGUR")||s.equals("1")?"successMessage":"errorMessage",String.valueOf(r.getOrDefault("mesaj",f)));}private String redirect(Long b,Long q){String u="redirect:/xidmetQiymetleri";if(b!=null)u+="?basliqId="+b;if(q!=null)u+="&qrupId="+q;return u;}
}
