package az.simplexs.simplexs.controller;
import java.util.*;import org.springframework.context.*;import org.springframework.context.i18n.*;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.stereotype.Controller;import org.springframework.ui.Model;import org.springframework.web.bind.annotation.*;import org.springframework.web.servlet.mvc.support.RedirectAttributes;
import az.simplexs.simplexs.dto.xeste.XesteForm;import az.simplexs.simplexs.repository.teskilat.TeskilatRepository;import az.simplexs.simplexs.repository.xeste.XesteRepository;import az.simplexs.simplexs.security.AuthenticatedPersonal;import jakarta.servlet.http.HttpSession;
@Controller @RequestMapping("/xeste-qeydiyyati") public class XesteQeydiyyatiController{
 private static final int DEFAULT_SIZE=25;private static final Set<Integer> ALLOWED_SIZES=Set.of(25,50,100);private final XesteRepository repo;private final TeskilatRepository teskilatRepo;private final MessageSource messages;
 public XesteQeydiyyatiController(XesteRepository repo,TeskilatRepository teskilatRepo,MessageSource messages){this.repo=repo;this.teskilatRepo=teskilatRepo;this.messages=messages;}
 @GetMapping public String siyahi(@RequestParam(required=false)String q,@RequestParam(defaultValue="aktiv")String status,@RequestParam(required=false)Long teskilatId,@RequestParam(required=false)Long cursor,@RequestParam(defaultValue="25")int size,Model m,HttpSession s){size=ALLOWED_SIZES.contains(size)?size:DEFAULT_SIZE;Boolean aktiv=status.isBlank()?null:!"passiv".equals(status);Long k=klinika(s);List<az.simplexs.simplexs.dto.xeste.Xeste> rows=repo.siyahi(k,aktiv,q,teskilatId,cursor,size+1);boolean hasNext=rows.size()>size;List<az.simplexs.simplexs.dto.xeste.Xeste> xesteler=hasNext?rows.subList(0,size):rows;Long nextCursor=hasNext?xesteler.getLast().id():null;m.addAttribute("pageTitle",msg("patients.title"));m.addAttribute("activeMenuGroup","pasientQebulu");m.addAttribute("activeMenu","xesteQeydiyyati");m.addAttribute("xesteler",xesteler);m.addAttribute("q",q);m.addAttribute("selectedStatus",status);m.addAttribute("selectedTeskilatId",teskilatId);m.addAttribute("selectedSize",size);m.addAttribute("filterApplied",(q!=null&&!q.isBlank())||!"aktiv".equals(status)||teskilatId!=null||size!=DEFAULT_SIZE);m.addAttribute("hasNext",hasNext);m.addAttribute("nextCursor",nextCursor);m.addAttribute("count",xesteler.size());lookups(m,k);return "pages/pasienQebulu/xesteQeydiyyati";}
 @PostMapping("/yeni") public String yarat(@ModelAttribute XesteForm form,HttpSession s,@AuthenticationPrincipal AuthenticatedPersonal p,RedirectAttributes f){result(repo.yarat(klinika(s),form,p.personalId()),f,msg("patients.created"));return back();}
 @PostMapping("/yenile") public String yenile(@ModelAttribute XesteForm form,HttpSession s,@AuthenticationPrincipal AuthenticatedPersonal p,RedirectAttributes f){result(repo.yenile(klinika(s),form,p.personalId()),f,msg("patients.updated"));return back();}
 @GetMapping("/yeni") public String yeni(Model m,HttpSession s){formBase(m,s,null);return "pages/pasienQebulu/xesteFormu";}
 @GetMapping("/{id}") public String redakte(@PathVariable Long id,Model m,HttpSession s){formBase(m,s,repo.tap(klinika(s),id));return "pages/pasienQebulu/xesteFormu";}
 private void formBase(Model m,HttpSession s,az.simplexs.simplexs.dto.xeste.Xeste x){m.addAttribute("pageTitle",msg(x==null?"patients.new":"patients.edit"));m.addAttribute("activeMenuGroup","pasientQebulu");m.addAttribute("activeMenu","xesteQeydiyyati");m.addAttribute("xeste",x);lookups(m,klinika(s));}
 private void lookups(Model m,Long k){m.addAttribute("teskilatlar",teskilatRepo.siyahi(k).stream().filter(x->Boolean.TRUE.equals(x.aktiv())).toList());m.addAttribute("vesiqeNovleri",repo.vesiqeNovleri());m.addAttribute("cinsler",repo.cinsler());m.addAttribute("aileVeziyyetleri",repo.aileVeziyyetleri());m.addAttribute("tehsiller",repo.tehsiller());m.addAttribute("qanQruplari",repo.qanQruplari());m.addAttribute("olkeler",repo.olkeler());m.addAttribute("seherler",repo.seherler());}
 private Long klinika(HttpSession s){return (Long)s.getAttribute(KlinikaController.SELECTED_KLINIKA_ID);}private String back(){return "redirect:/xeste-qeydiyyati";}private String msg(String k){return messages.getMessage(k,null,LocaleContextHolder.getLocale());}private void result(Map<String,Object> r,RedirectAttributes f,String fallback){String status=String.valueOf(r.getOrDefault("status_kodu",""));String message=String.valueOf(r.getOrDefault("mesaj",fallback));f.addFlashAttribute(status.toUpperCase().contains("UGUR")||"1".equals(status)?"successMessage":"errorMessage",message);}
}
