package az.simplexs.simplexs.repository.qiymet;
import java.sql.*;import java.util.*;import org.springframework.jdbc.core.namedparam.*;import org.springframework.stereotype.Repository;import az.simplexs.simplexs.dto.qiymet.*;
@Repository public class QiymetRepository{
 private final NamedParameterJdbcTemplate jdbc;public QiymetRepository(NamedParameterJdbcTemplate jdbc){this.jdbc=jdbc;}
 public List<QiymetBasligi> basliqlar(){return jdbc.query("SELECT * FROM public.fn_qiymet_basligi_siyahisi() ORDER BY sira_no NULLS LAST,qiymet_basligi_adi",(r,n)->new QiymetBasligi(l(r,"qiymet_basligi_id"),r.getString("qiymet_basligi_adi"),r.getString("aciqlama"),i(r,"sira_no")));}
 public List<QiymetQrupu> qruplar(Long basliqId){return jdbc.query("SELECT * FROM public.fn_qiymet_qrupu_siyahisi(CAST(:id AS bigint),CAST(:aktiv AS boolean),CAST(:tarix AS boolean)) ORDER BY sira_no NULLS LAST,qiymet_qrupu_adi",new MapSqlParameterSource().addValue("id",basliqId).addValue("aktiv",null).addValue("tarix",null),(r,n)->new QiymetQrupu(l(r,"qiymet_qrupu_id"),l(r,"qiymet_basligi_id"),r.getString("qiymet_basligi_adi"),r.getString("qiymet_qrupu_adi"),r.getString("aciqlama"),r.getObject("baslama_tarixi",java.time.LocalDate.class),r.getObject("bitme_tarixi",java.time.LocalDate.class),r.getObject("tarixde_aktivdir",Boolean.class),i(r,"sira_no"),r.getObject("aktiv",Boolean.class)));}
 public List<QiymetXidmeti> xidmetler(Long qrupId,Long xidmetQrupuId){if(qrupId==null)return List.of();return jdbc.query("SELECT * FROM public.fn_qiymet_qrupu_xidmet_siyahisi(CAST(:q AS bigint),CAST(:x AS bigint),true) ORDER BY xidmet_qrupu_adi,xidmet_sira_no NULLS LAST,xidmet_adi",new MapSqlParameterSource().addValue("q",qrupId).addValue("x",xidmetQrupuId),(r,n)->new QiymetXidmeti(l(r,"xidmet_id"),r.getString("xidmet_kodu"),r.getString("xidmet_adi"),l(r,"xidmet_qrupu_id"),r.getString("xidmet_qrupu_adi"),r.getString("xidmet_tipi_adi"),l(r,"xidmet_qiymeti_id"),r.getBigDecimal("qiymet"),r.getBigDecimal("xeste_pay_faizi"),r.getBigDecimal("qurum_pay_faizi"),r.getBigDecimal("xeste_endirim_faizi"),r.getBigDecimal("qurum_endirim_faizi"),r.getObject("edv_aktivdir",Boolean.class),r.getObject("qiymet_aktiv",Boolean.class),r.getObject("qiymet_teyin_edilib",Boolean.class)));}
 public List<QiymetXidmeti> xidmetler(Long qrupId,Long xidmetQrupuId,String query,String qiymetStatus,int limit,int offset){String sql="SELECT * FROM public.fn_qiymet_qrupu_xidmet_siyahisi(CAST(:q AS bigint),CAST(:x AS bigint),true) f WHERE (CAST(:axtar AS text) IS NULL OR f.xidmet_adi ILIKE '%'||CAST(:axtar AS text)||'%' OR f.xidmet_kodu ILIKE '%'||CAST(:axtar AS text)||'%') AND (CAST(:status AS text) IS NULL OR (CAST(:status AS text)='teyin' AND f.qiymet_teyin_edilib=true) OR (CAST(:status AS text)='teyin_deyil' AND f.qiymet_teyin_edilib=false)) ORDER BY f.xidmet_qrupu_adi,f.xidmet_sira_no NULLS LAST,f.xidmet_adi LIMIT :limit OFFSET :offset";return jdbc.query(sql,filterParams(qrupId,xidmetQrupuId,query,qiymetStatus).addValue("limit",limit).addValue("offset",offset),(r,n)->mapXidmet(r));}
 public long xidmetSayi(Long qrupId,Long xidmetQrupuId,String query,String qiymetStatus){return jdbc.queryForObject("SELECT count(*) FROM public.fn_qiymet_qrupu_xidmet_siyahisi(CAST(:q AS bigint),CAST(:x AS bigint),true) f WHERE (CAST(:axtar AS text) IS NULL OR f.xidmet_adi ILIKE '%'||CAST(:axtar AS text)||'%' OR f.xidmet_kodu ILIKE '%'||CAST(:axtar AS text)||'%') AND (CAST(:status AS text) IS NULL OR (CAST(:status AS text)='teyin' AND f.qiymet_teyin_edilib=true) OR (CAST(:status AS text)='teyin_deyil' AND f.qiymet_teyin_edilib=false))",filterParams(qrupId,xidmetQrupuId,query,qiymetStatus),Long.class);}
 public Map<String,Object> basliqYarat(String ad){return one("SELECT * FROM public.fn_qiymet_basligi_yarat(p_ad=>:ad,p_yaradan_personal_id=>NULL)",new MapSqlParameterSource("ad",ad.trim()));}
 public Map<String,Object> basliqYenile(Long id,String ad,String aciqlama,Integer sira,boolean aktiv){return one("SELECT * FROM public.fn_qiymet_basligi_yenile(p_qiymet_basligi_id=>:id,p_ad=>:ad,p_aciqlama=>:aciq,p_aciqlama_deyisdirilsin=>true,p_sira_no=>:sira,p_aktiv=>:aktiv,p_yenileyen_personal_id=>NULL)",new MapSqlParameterSource().addValue("id",id).addValue("ad",ad.trim()).addValue("aciq",blank(aciqlama)).addValue("sira",sira).addValue("aktiv",aktiv));}
 public Map<String,Object> qrupYarat(Long basliq,String ad,java.time.LocalDate bas,java.time.LocalDate bit,String aciq,Integer sira,Long klon){return one("SELECT * FROM public.fn_qiymet_qrupu_yarat(p_qiymet_basligi_id=>:b,p_ad=>:ad,p_baslama_tarixi=>:bas,p_bitme_tarixi=>:bit,p_aciqlama=>:aciq,p_sira_no=>:sira,p_klon_qiymet_qrupu_id=>:klon,p_yaradan_personal_id=>NULL)",new MapSqlParameterSource().addValue("b",basliq).addValue("ad",ad.trim()).addValue("bas",bas).addValue("bit",bit).addValue("aciq",blank(aciq)).addValue("sira",sira).addValue("klon",klon));}
 public Map<String,Object> qrupYenile(Long id,Long basliq,String ad,String aciq,java.time.LocalDate bas,java.time.LocalDate bit,Integer sira,boolean aktiv){return one("SELECT * FROM public.fn_qiymet_qrupu_yenile(p_qiymet_qrupu_id=>:id,p_qiymet_basligi_id=>:b,p_ad=>:ad,p_aciqlama=>:aciq,p_aciqlama_deyisdirilsin=>true,p_baslama_tarixi=>:bas,p_bitme_tarixi=>:bit,p_sira_no=>:sira,p_aktiv=>:aktiv,p_yenileyen_personal_id=>NULL)",new MapSqlParameterSource().addValue("id",id).addValue("b",basliq).addValue("ad",ad.trim()).addValue("aciq",blank(aciq)).addValue("bas",bas).addValue("bit",bit).addValue("sira",sira).addValue("aktiv",aktiv));}
 public Map<String,Object> qiymetSaxla(Long qrup,Long xidmet,java.math.BigDecimal qiymet,java.math.BigDecimal xestePay,java.math.BigDecimal xesteEndirim,java.math.BigDecimal qurumEndirim,boolean edv){String json="[{\"xidmet_id\":"+xidmet+",\"qiymet\":"+qiymet+",\"xeste_pay_faizi\":"+nz(xestePay)+",\"xeste_endirim_faizi\":"+nz(xesteEndirim)+",\"qurum_endirim_faizi\":"+nz(qurumEndirim)+",\"edv_aktivdir\":"+edv+"}]";return one("SELECT * FROM public.fn_xidmet_qiymetlerini_yadda_saxla(p_qiymet_qrupu_id=>:q,p_qiymetler=>CAST(:json AS jsonb),p_emel_eden_personal_id=>NULL)",new MapSqlParameterSource().addValue("q",qrup).addValue("json",json));}
 public Map<String,Object> qiymetleriSaxla(Long qrup,String json){return one("SELECT * FROM public.fn_xidmet_qiymetlerini_yadda_saxla(p_qiymet_qrupu_id=>:q,p_qiymetler=>CAST(:json AS jsonb),p_emel_eden_personal_id=>NULL)",new MapSqlParameterSource().addValue("q",qrup).addValue("json",json));}
 private MapSqlParameterSource filterParams(Long q,Long x,String a,String s){return new MapSqlParameterSource().addValue("q",q).addValue("x",x).addValue("axtar",blank(a)).addValue("status",blank(s));}
 private QiymetXidmeti mapXidmet(ResultSet r)throws SQLException{return new QiymetXidmeti(l(r,"xidmet_id"),r.getString("xidmet_kodu"),r.getString("xidmet_adi"),l(r,"xidmet_qrupu_id"),r.getString("xidmet_qrupu_adi"),r.getString("xidmet_tipi_adi"),l(r,"xidmet_qiymeti_id"),r.getBigDecimal("qiymet"),r.getBigDecimal("xeste_pay_faizi"),r.getBigDecimal("qurum_pay_faizi"),r.getBigDecimal("xeste_endirim_faizi"),r.getBigDecimal("qurum_endirim_faizi"),r.getObject("edv_aktivdir",Boolean.class),r.getObject("qiymet_aktiv",Boolean.class),r.getObject("qiymet_teyin_edilib",Boolean.class));}
 private static java.math.BigDecimal nz(java.math.BigDecimal x){return x==null?java.math.BigDecimal.ZERO:x;}private Map<String,Object> one(String s,MapSqlParameterSource p){var rows=jdbc.queryForList(s,p);return rows.isEmpty()?Map.of():rows.getFirst();}private static String blank(String s){return s==null||s.isBlank()?null:s.trim();}private static Long l(ResultSet r,String c)throws SQLException{Object x=r.getObject(c);return x instanceof Number n?n.longValue():null;}private static Integer i(ResultSet r,String c)throws SQLException{Object x=r.getObject(c);return x instanceof Number n?n.intValue():null;}
}
