package az.simplexs.simplexs.repository.qiymet;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;
import az.simplexs.simplexs.dto.qiymet.QiymetBasligi;
import az.simplexs.simplexs.dto.qiymet.QiymetQrupu;
import az.simplexs.simplexs.dto.qiymet.QiymetXidmeti;

@Repository
public class QiymetRepository {
    private final NamedParameterJdbcTemplate jdbc;
    public QiymetRepository(NamedParameterJdbcTemplate jdbc){this.jdbc=jdbc;}

    public List<QiymetBasligi> basliqlar(Long klinikaId){return jdbc.query("SELECT * FROM public.fn_qiymet_basligi_siyahisi(CAST(:klinika AS bigint)) ORDER BY sira_no NULLS LAST,qiymet_basligi_adi",new MapSqlParameterSource("klinika",klinikaId),(r,n)->new QiymetBasligi(l(r,"qiymet_basligi_id"),r.getString("qiymet_basligi_adi"),r.getString("aciqlama"),i(r,"sira_no")));}
    public List<QiymetQrupu> qruplar(Long klinikaId,Long basliqId){return jdbc.query("SELECT * FROM public.fn_qiymet_qrupu_siyahisi(p_klinika_id=>CAST(:klinika AS bigint),p_qiymet_basligi_id=>CAST(:id AS bigint),p_aktiv=>CAST(:aktiv AS boolean),p_tarixde_aktivdir=>CAST(:tarix AS boolean)) ORDER BY sira_no NULLS LAST,qiymet_qrupu_adi",new MapSqlParameterSource().addValue("klinika",klinikaId).addValue("id",basliqId).addValue("aktiv",null).addValue("tarix",null),(r,n)->new QiymetQrupu(l(r,"qiymet_qrupu_id"),l(r,"klinika_id"),l(r,"qiymet_basligi_id"),r.getString("qiymet_basligi_adi"),r.getString("qiymet_qrupu_adi"),r.getString("aciqlama"),r.getObject("baslama_tarixi",java.time.LocalDate.class),r.getObject("bitme_tarixi",java.time.LocalDate.class),r.getObject("tarixde_aktivdir",Boolean.class),r.getObject("standartdir",Boolean.class),r.getBigDecimal("sigorta_payi"),r.getBigDecimal("xeste_payi"),r.getBigDecimal("sigorta_endirim"),r.getBigDecimal("xeste_endirim"),i(r,"sira_no"),r.getObject("aktiv",Boolean.class)));}
    public List<QiymetXidmeti> xidmetler(Long qrupId,Long xidmetQrupuId,String query,String status,int limit,int offset){String sql="SELECT * FROM public.fn_qiymet_qrupu_xidmet_siyahisi(CAST(:q AS bigint),CAST(:x AS bigint),true) f WHERE (CAST(:axtar AS text) IS NULL OR f.xidmet_adi ILIKE '%'||CAST(:axtar AS text)||'%' OR f.xidmet_kodu ILIKE '%'||CAST(:axtar AS text)||'%') AND (CAST(:status AS text) IS NULL OR (CAST(:status AS text)='teyin' AND f.qiymet_teyin_edilib=true) OR (CAST(:status AS text)='teyin_deyil' AND f.qiymet_teyin_edilib=false)) ORDER BY f.xidmet_qrupu_adi,f.xidmet_sira_no NULLS LAST,f.xidmet_adi LIMIT :limit OFFSET :offset";return jdbc.query(sql,filterParams(qrupId,xidmetQrupuId,query,status).addValue("limit",limit).addValue("offset",offset),(r,n)->mapXidmet(r));}
    public long xidmetSayi(Long qrupId,Long xidmetQrupuId,String query,String status){return jdbc.queryForObject("SELECT count(*) FROM public.fn_qiymet_qrupu_xidmet_siyahisi(CAST(:q AS bigint),CAST(:x AS bigint),true) f WHERE (CAST(:axtar AS text) IS NULL OR f.xidmet_adi ILIKE '%'||CAST(:axtar AS text)||'%' OR f.xidmet_kodu ILIKE '%'||CAST(:axtar AS text)||'%') AND (CAST(:status AS text) IS NULL OR (CAST(:status AS text)='teyin' AND f.qiymet_teyin_edilib=true) OR (CAST(:status AS text)='teyin_deyil' AND f.qiymet_teyin_edilib=false))",filterParams(qrupId,xidmetQrupuId,query,status),Long.class);}

    public Map<String,Object> basliqYarat(Long klinikaId,String ad,String aciqlama){return one("SELECT * FROM public.fn_qiymet_basligi_yarat(p_klinika_id=>:klinika,p_ad=>:ad,p_aciqlama=>:aciq,p_yaradan_personal_id=>NULL)",new MapSqlParameterSource().addValue("klinika",klinikaId).addValue("ad",ad.trim()).addValue("aciq",blank(aciqlama)));}
    public Map<String,Object> basliqYenile(Long id,String ad,String aciqlama,boolean aktiv){return one("SELECT * FROM public.fn_qiymet_basligi_yenile(p_qiymet_basligi_id=>:id,p_ad=>:ad,p_aciqlama=>:aciq,p_aciqlama_deyisdirilsin=>true,p_aktiv=>:aktiv,p_yenileyen_personal_id=>NULL)",new MapSqlParameterSource().addValue("id",id).addValue("ad",ad.trim()).addValue("aciq",blank(aciqlama)).addValue("aktiv",aktiv));}

    public Map<String,Object> qrupYarat(Long basliq,String ad,java.time.LocalDate bas,java.time.LocalDate bit,String aciq,Long klon,List<Long> ids,Long klinikaId,boolean standartdir,java.math.BigDecimal xestePayi,java.math.BigDecimal sigortaPayi,java.math.BigDecimal xesteEndirimi,java.math.BigDecimal sigortaEndirimi){String sql="SELECT * FROM public.fn_qiymet_qrupu_yarat(p_klinika_id=>:klinika,p_qiymet_basligi_id=>:b,p_ad=>:ad,p_baslama_tarixi=>:bas,p_bitme_tarixi=>:bit,p_aciqlama=>:aciq,p_standartdir=>:standart,p_klon_qiymet_qrupu_id=>:klon,p_xeste_payi=>:xp,p_sigorta_payi=>:sp,p_xeste_endirim=>:xe,p_sigorta_endirim=>:se,p_teskilat_idleri=>CAST(:teskilatlar AS bigint[]),p_yaradan_personal_id=>NULL)";return one(sql,qrupParams(basliq,ad,bas,bit,aciq,ids,xestePayi,sigortaPayi,xesteEndirimi,sigortaEndirimi).addValue("klinika",klinikaId).addValue("standart",standartdir).addValue("klon",klon));}
    public Map<String,Object> qrupYenile(Long id,String ad,String aciq,java.time.LocalDate bas,java.time.LocalDate bit,boolean standartdir,boolean aktiv,List<Long> ids,java.math.BigDecimal xestePayi,java.math.BigDecimal sigortaPayi,java.math.BigDecimal xesteEndirimi,java.math.BigDecimal sigortaEndirimi){String sql="SELECT * FROM public.fn_qiymet_qrupu_yenile(p_qiymet_qrupu_id=>:id,p_ad=>:ad,p_aciqlama=>:aciq,p_aciqlama_deyisdirilsin=>true,p_baslama_tarixi=>:bas,p_bitme_tarixi=>:bit,p_standartdir=>:standart,p_standartdir_deyisdirilsin=>true,p_xeste_payi=>:xp,p_xeste_payi_deyisdirilsin=>true,p_sigorta_payi=>:sp,p_sigorta_payi_deyisdirilsin=>true,p_xeste_endirim=>:xe,p_xeste_endirim_deyisdirilsin=>true,p_sigorta_endirim=>:se,p_sigorta_endirim_deyisdirilsin=>true,p_teskilat_idleri=>CAST(:teskilatlar AS bigint[]),p_teskilatlar_deyisdirilsin=>true,p_aktiv=>:aktiv,p_yenileyen_personal_id=>NULL)";return one(sql,qrupParams(null,ad,bas,bit,aciq,ids,xestePayi,sigortaPayi,xesteEndirimi,sigortaEndirimi).addValue("id",id).addValue("standart",standartdir).addValue("aktiv",aktiv));}

    public Map<String,Object> qiymetSaxla(Long qrup,Long xidmet,java.math.BigDecimal qiymet,java.math.BigDecimal xestePay,java.math.BigDecimal xesteEndirim,java.math.BigDecimal qurumEndirim,boolean edv){String json="[{\"xidmet_id\":"+xidmet+",\"qiymet\":"+qiymet+",\"xeste_pay_faizi\":"+nz(xestePay)+",\"xeste_endirim_faizi\":"+nz(xesteEndirim)+",\"qurum_endirim_faizi\":"+nz(qurumEndirim)+",\"edv_aktivdir\":"+edv+"}]";return one("SELECT * FROM public.fn_xidmet_qiymetlerini_yadda_saxla(p_qiymet_qrupu_id=>:q,p_qiymetler=>CAST(:json AS jsonb),p_emel_eden_personal_id=>NULL)",new MapSqlParameterSource().addValue("q",qrup).addValue("json",json));}
    public Map<String,Object> qiymetleriSaxla(Long qrup,String json){return one("SELECT * FROM public.fn_xidmet_qiymetlerini_yadda_saxla(p_qiymet_qrupu_id=>:q,p_qiymetler=>CAST(:json AS jsonb),p_emel_eden_personal_id=>NULL)",new MapSqlParameterSource().addValue("q",qrup).addValue("json",json));}

    public Map<Long,List<Long>> qruplarinTeskilatIdleri(List<Long> qrupIds){Map<Long,List<Long>> result=new LinkedHashMap<>();if(qrupIds==null)return result;for(Long id:qrupIds){List<Long> ids=jdbc.query("SELECT teskilat_id FROM public.fn_qiymet_qrupu_teskilat_siyahisi(p_qiymet_qrupu_id=>CAST(:id AS bigint),p_aktiv=>true)",new MapSqlParameterSource("id",id),(r,n)->r.getLong("teskilat_id"));result.put(id,ids);}return result;}

    private MapSqlParameterSource qrupParams(Long b,String ad,java.time.LocalDate bas,java.time.LocalDate bit,String aciq,List<Long> ids,java.math.BigDecimal xp,java.math.BigDecimal sp,java.math.BigDecimal xe,java.math.BigDecimal se){return new MapSqlParameterSource().addValue("b",b).addValue("ad",ad.trim()).addValue("bas",bas).addValue("bit",bit).addValue("aciq",blank(aciq)).addValue("teskilatlar",arrayLiteral(ids)).addValue("xp",nz(xp)).addValue("sp",nz(sp)).addValue("xe",nz(xe)).addValue("se",nz(se));}
    private String arrayLiteral(List<Long> ids){if(ids==null||ids.isEmpty())return "{}";return ids.stream().map(String::valueOf).collect(java.util.stream.Collectors.joining(",","{","}"));}
    private MapSqlParameterSource filterParams(Long q,Long x,String a,String s){return new MapSqlParameterSource().addValue("q",q).addValue("x",x).addValue("axtar",blank(a)).addValue("status",blank(s));}
    private QiymetXidmeti mapXidmet(ResultSet r)throws SQLException{return new QiymetXidmeti(l(r,"xidmet_id"),r.getString("xidmet_kodu"),r.getString("xidmet_adi"),l(r,"xidmet_qrupu_id"),r.getString("xidmet_qrupu_adi"),r.getString("xidmet_tipi_adi"),l(r,"xidmet_qiymeti_id"),r.getBigDecimal("qiymet"),r.getBigDecimal("xeste_pay_faizi"),r.getBigDecimal("qurum_pay_faizi"),r.getBigDecimal("xeste_endirim_faizi"),r.getBigDecimal("qurum_endirim_faizi"),r.getObject("edv_aktivdir",Boolean.class),r.getObject("qiymet_aktiv",Boolean.class),r.getObject("qiymet_teyin_edilib",Boolean.class));}
    private Map<String,Object> one(String sql,MapSqlParameterSource p){List<Map<String,Object>> rows=jdbc.queryForList(sql,p);return rows.isEmpty()?Map.of():rows.getFirst();}
    private static String blank(String s){return s==null||s.isBlank()?null:s.trim();}
    private static java.math.BigDecimal nz(java.math.BigDecimal x){return x==null?java.math.BigDecimal.ZERO:x;}
    private static Long l(ResultSet r,String c)throws SQLException{Object x=r.getObject(c);return x instanceof Number n?n.longValue():null;}
    private static Integer i(ResultSet r,String c)throws SQLException{Object x=r.getObject(c);return x instanceof Number n?n.intValue():null;}
}
