-- Tətbiq xətalarının təhlükəsiz və dəyişməz jurnalını saxlayır.
CREATE TABLE IF NOT EXISTS public.kn_xeta_jurnali (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    xeta_kodu varchar(20) NOT NULL UNIQUE,
    xeta_novu varchar(50) NOT NULL,
    personal_id bigint NULL REFERENCES public.rn_personallar(id),
    istifadeci_adi varchar(150),
    klinika_id bigint,
    route varchar(500),
    http_metod varchar(10),
    ip_unvan varchar(64),
    exception_sinfi varchar(300),
    qisa_aciqlama varchar(1000),
    yaranma_tarixi timestamp NOT NULL DEFAULT current_timestamp
);

COMMENT ON TABLE public.kn_xeta_jurnali IS 'İstifadəçiyə göstərilən xəta kodlarının təhlükəsiz texniki jurnalını saxlayır.';
COMMENT ON COLUMN public.kn_xeta_jurnali.xeta_kodu IS 'İstifadəçiyə göstərilən unikal xəta kodu.';
COMMENT ON COLUMN public.kn_xeta_jurnali.xeta_novu IS 'DB, sistem və digər texniki xəta kateqoriyası.';
COMMENT ON COLUMN public.kn_xeta_jurnali.qisa_aciqlama IS 'Həssas məlumat və stack trace olmadan qısa texniki səbəb.';
COMMENT ON COLUMN public.kn_xeta_jurnali.yaranma_tarixi IS 'Xətanın qeydə alındığı tarix və saat.';

CREATE INDEX IF NOT EXISTS ix_kn_xeta_jurnali_tarix ON public.kn_xeta_jurnali(yaranma_tarixi DESC);
COMMENT ON INDEX public.ix_kn_xeta_jurnali_tarix IS 'Xəta jurnalının tarix üzrə sürətli sıralanmasını təmin edir.';

-- Xəta qeydini jurnala yazır və yaradılmış qeyd ID-sini qaytarır.
CREATE OR REPLACE FUNCTION public.kn_xeta_jurnali_yaz(
    p_xeta_kodu varchar, p_xeta_novu varchar, p_personal_id bigint,
    p_istifadeci_adi varchar, p_klinika_id bigint, p_route varchar,
    p_http_metod varchar, p_ip_unvan varchar, p_exception_sinfi varchar,
    p_qisa_aciqlama varchar
) RETURNS bigint LANGUAGE plpgsql AS $$
DECLARE v_id bigint;
BEGIN
    INSERT INTO public.kn_xeta_jurnali(xeta_kodu,xeta_novu,personal_id,istifadeci_adi,
        klinika_id,route,http_metod,ip_unvan,exception_sinfi,qisa_aciqlama)
    VALUES(upper(trim(p_xeta_kodu)),upper(trim(p_xeta_novu)),p_personal_id,
        nullif(trim(p_istifadeci_adi),''),p_klinika_id,nullif(trim(p_route),''),
        nullif(upper(trim(p_http_metod)),''),nullif(trim(p_ip_unvan),''),
        left(nullif(trim(p_exception_sinfi),''),300),left(nullif(trim(p_qisa_aciqlama),''),1000))
    RETURNING id INTO v_id;
    RETURN v_id;
END; $$;
COMMENT ON FUNCTION public.kn_xeta_jurnali_yaz(varchar,varchar,bigint,varchar,bigint,varchar,varchar,varchar,varchar,varchar)
IS 'Mərkəzi xəta handler-inin yaratdığı təhlükəsiz xəta qeydini jurnala yazır.';

-- Xəta jurnalını filtr və səhifələmə ilə qaytarır.
CREATE OR REPLACE FUNCTION public.kn_xeta_jurnali_siyahisi(
    p_klinika_id bigint, p_xeta_novu varchar, p_axtaris varchar,
    p_baslama_tarixi date, p_bitme_tarixi date, p_limit integer, p_offset integer
) RETURNS TABLE(id bigint,xeta_kodu varchar,xeta_novu varchar,personal_id bigint,
    istifadeci_adi varchar,klinika_id bigint,route varchar,http_metod varchar,
    ip_unvan varchar,exception_sinfi varchar,qisa_aciqlama varchar,
    yaranma_tarixi timestamp,total_sayi bigint)
LANGUAGE sql STABLE AS $$
    SELECT x.id,x.xeta_kodu,x.xeta_novu,x.personal_id,x.istifadeci_adi,x.klinika_id,
           x.route,x.http_metod,x.ip_unvan,x.exception_sinfi,x.qisa_aciqlama,
           x.yaranma_tarixi,count(*) OVER()
    FROM public.kn_xeta_jurnali x
    WHERE (p_klinika_id IS NULL OR x.klinika_id=p_klinika_id)
      AND (nullif(trim(p_xeta_novu),'') IS NULL OR x.xeta_novu=upper(trim(p_xeta_novu)))
      AND (p_baslama_tarixi IS NULL OR x.yaranma_tarixi>=p_baslama_tarixi)
      AND (p_bitme_tarixi IS NULL OR x.yaranma_tarixi<p_bitme_tarixi+1)
      AND (nullif(trim(p_axtaris),'') IS NULL OR x.xeta_kodu ILIKE '%'||trim(p_axtaris)||'%'
           OR x.route ILIKE '%'||trim(p_axtaris)||'%' OR x.istifadeci_adi ILIKE '%'||trim(p_axtaris)||'%')
    ORDER BY x.yaranma_tarixi DESC
    LIMIT greatest(coalesce(p_limit,50),1) OFFSET greatest(coalesce(p_offset,0),0);
$$;
COMMENT ON FUNCTION public.kn_xeta_jurnali_siyahisi(bigint,varchar,varchar,date,date,integer,integer)
IS 'Xəta jurnalını klinika, növ, tarix və axtarış filtrləri ilə səhifələyir.';

-- Parametrlər altında funksional xəta jurnalı modulunu və baxış icazəsini qeydə alır.
WITH parent AS (SELECT id,sistem_id FROM public.rn_modullar WHERE kod='MIS_PARAM')
INSERT INTO public.rn_modullar(sistem_id,parent_id,kod,ad,aciqlama,route,ikon,menyuda_gorunsun,aktiv,sira_no)
SELECT sistem_id,id,'MIS_ERROR_LOG','Xəta jurnalı','Sistem xətalarının baxış jurnalı','/xetaJurnali','ti ti-alert-triangle',true,true,95 FROM parent
ON CONFLICT(kod) DO UPDATE SET parent_id=EXCLUDED.parent_id,sistem_id=EXCLUDED.sistem_id,ad=EXCLUDED.ad,
 route=EXCLUDED.route,ikon=EXCLUDED.ikon,menyuda_gorunsun=true,aktiv=true;

INSERT INTO public.rn_selahiyyetler(modul_id,kod,ad,aktiv)
SELECT id,'XETA_JURNALI_BAX','Xəta jurnalına bax',true FROM public.rn_modullar WHERE kod='MIS_ERROR_LOG'
ON CONFLICT(kod) DO UPDATE SET modul_id=EXCLUDED.modul_id,ad=EXCLUDED.ad,aktiv=true;

INSERT INTO public.rn_route_selahiyyetleri(route,http_metod,selahiyyet_kodu,aktiv)
VALUES('/xetaJurnali','GET','XETA_JURNALI_BAX',true)
ON CONFLICT(route,http_metod) DO UPDATE SET selahiyyet_kodu=EXCLUDED.selahiyyet_kodu,aktiv=true;
