spring.application.name=SImplexS

server.port=9099
server.address=0.0.0.0

spring.datasource.url=${SIMPLEXS_DB_URL:jdbc:postgresql://REMOVED_DB_HOST:5432/SimplexS}
spring.datasource.username=${SIMPLEXS_DB_USERNAME:postgres}
spring.datasource.password=${SIMPLEXS_DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
