spring.datasource.url=jdbc:postgresql://65.109.84.169:5432/Carelix
spring.datasource.username=BEITBR
spring.datasource.password=1qa2ws3ed

# Development settings for immediate HTML/CSS/JS refresh
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false