package az.simplexs.simplexs.repository.anbar;

import static az.simplexs.simplexs.dto.anbar.AnbarModels.*;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.Map;

import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
public class AnbarRepository {
    private final NamedParameterJdbcTemplate jdbc;
    public AnbarRepository(NamedParameterJdbcTemplate jdbc){this.jdbc=jdbc;}
    private MapSqlParameterSource p(){return new MapSqlParameterSource();}
    private List<Map<String,Object>> call(String sql,MapSqlParameterSource p){return jdbc.queryForList(sql,p);}
    private Map<String,Object> one(String sql,MapSqlParameterSource p){var rows=call(sql,p);return rows.isEmpty()?Map.of():rows.getFirst();}
    private static String n(String s){return s==null||s.isBlank()?null:s.trim();}

    public List<Firma> firmalar(Boolean aktiv){return jdbc.query("SELECT * FROM public.fn_firma_siyahisi(CAST(:a AS boolean)) ORDER BY ad",p().addValue("a",aktiv),(r,i)->new Firma(l(r,"firma_id"),s(r,"musteri_nomresi"),s(r,"ad"),s(r,"unvan"),s(r,"is_telefonu"),s(r,"faks_nomresi"),s(r,"email"),s(r,"qeyd"),s(r,"bank_adi"),s(r,"bank_hesab_nomresi"),s(r,"vergi_nomresi"),s(r,"vergi_idaresi"),b(r,"aktiv"),dt(r,"yaranma_tarixi"),dt(r,"yenilenme_tarixi")));}
    public Map<String,Object> firmaYarat(Long k,String ad,String musteri,String unvan,String telefon,String faks,String email,String qeyd,String bank,String hesab,String vergi,String idare,Long personal){return one("SELECT * FROM public.fn_firma_yarat(p_klinika_id=>CAST(:k AS bigint),p_ad=>:ad,p_musteri_nomresi=>:m,p_unvan=>:u,p_is_telefonu=>:t,p_faks_nomresi=>:f,p_email=>:e,p_qeyd=>:q,p_bank_adi=>:b,p_bank_hesab_nomresi=>:h,p_vergi_nomresi=>:v,p_vergi_idaresi=>:i,p_yaradan_personal_id=>CAST(:p AS bigint))",p().addValue("k",k).addValue("ad",ad.trim()).addValue("m",n(musteri)).addValue("u",n(unvan)).addValue("t",n(telefon)).addValue("f",n(faks)).addValue("e",n(email)).addValue("q",n(qeyd)).addValue("b",n(bank)).addValue("h",n(hesab)).addValue("v",n(vergi)).addValue("i",n(idare)).addValue("p",personal));}
    public Map<String,Object> firmaYenile(Long k,Long id,String ad,String musteri,String unvan,String telefon,String faks,String email,String qeyd,String bank,String hesab,String vergi,String idare,boolean aktiv,Long personal){return one("SELECT * FROM public.fn_firma_yenile(p_klinika_id=>CAST(:k AS bigint),p_firma_id=>CAST(:id AS bigint),p_ad=>:ad,p_musteri_nomresi=>:m,p_musteri_nomresi_deyisdirilsin=>true,p_unvan=>:u,p_unvan_deyisdirilsin=>true,p_is_telefonu=>:t,p_is_telefonu_deyisdirilsin=>true,p_faks_nomresi=>:f,p_faks_nomresi_deyisdirilsin=>true,p_email=>:e,p_email_deyisdirilsin=>true,p_qeyd=>:q,p_qeyd_deyisdirilsin=>true,p_bank_adi=>:b,p_bank_adi_deyisdirilsin=>true,p_bank_hesab_nomresi=>:h,p_bank_hesab_nomresi_deyisdirilsin=>true,p_vergi_nomresi=>:v,p_vergi_nomresi_deyisdirilsin=>true,p_vergi_idaresi=>:i,p_vergi_idaresi_deyisdirilsin=>true,p_aktiv=>:a,p_yenileyen_personal_id=>CAST(:p AS bigint))",p().addValue("k",k).addValue("id",id).addValue("ad",ad.trim()).addValue("m",n(musteri)).addValue("u",n(unvan)).addValue("t",n(telefon)).addValue("f",n(faks)).addValue("e",n(email)).addValue("q",n(qeyd)).addValue("b",n(bank)).addValue("h",n(hesab)).addValue("v",n(vergi)).addValue("i",n(idare)).addValue("a",aktiv).addValue("p",personal));}

    public List<Vahid> vahidler(Boolean aktiv){return jdbc.query("SELECT * FROM public.fn_vahid_siyahisi(CAST(:a AS boolean),CAST(NULL AS boolean)) ORDER BY sira_no NULLS LAST,ad",p().addValue("a",aktiv),(r,i)->new Vahid(l(r,"vahid_id"),s(r,"ad"),l(r,"alt_vahid_id"),s(r,"alt_vahid_adi"),d(r,"vurma_emsali"),in(r,"sira_no"),b(r,"sifarisde_gorunsun"),b(r,"aktiv"),dt(r,"yaranma_tarixi"),dt(r,"yenilenme_tarixi")));}
    public Map<String,Object> vahidYarat(Long k,String ad,Long alt,java.math.BigDecimal emsal,boolean sifaris,Long personal){return one("SELECT * FROM public.fn_vahid_yarat(p_klinika_id=>CAST(:k AS bigint),p_ad=>:ad,p_alt_vahid_id=>CAST(:alt AS bigint),p_vurma_emsali=>CAST(:em AS numeric),p_sifarisde_gorunsun=>:s,p_yaradan_personal_id=>CAST(:p AS bigint))",p().addValue("k",k).addValue("ad",ad.trim()).addValue("alt",alt).addValue("em",emsal).addValue("s",sifaris).addValue("p",personal));}
    public Map<String,Object> vahidYenile(Long k,Long id,String ad,Long alt,java.math.BigDecimal emsal,boolean sifaris,boolean aktiv,Long personal){return one("SELECT * FROM public.fn_vahid_yenile(p_klinika_id=>CAST(:k AS bigint),p_vahid_id=>CAST(:id AS bigint),p_ad=>:ad,p_alt_vahid_id=>CAST(:alt AS bigint),p_alt_vahid_deyisdirilsin=>true,p_vurma_emsali=>CAST(:em AS numeric),p_vurma_emsali_deyisdirilsin=>true,p_sifarisde_gorunsun=>:s,p_aktiv=>:a,p_yenileyen_personal_id=>CAST(:p AS bigint))",p().addValue("k",k).addValue("id",id).addValue("ad",ad.trim()).addValue("alt",alt).addValue("em",emsal).addValue("s",sifaris).addValue("a",aktiv).addValue("p",personal));}

    public List<QrupNovu> qrupNovleri(){return jdbc.query("SELECT * FROM public.fn_mehsul_qrup_novu_siyahisi() ORDER BY sira_no NULLS LAST,ad",(r,i)->new QrupNovu(l(r,"qrup_novu_id"),s(r,"kod"),s(r,"ad"),s(r,"aciqlama"),in(r,"sira_no"),b(r,"aktiv")));}
    public List<MehsulQrupu> qruplar(Long k,Boolean aktiv){return jdbc.query("SELECT * FROM public.fn_mehsul_qrup_siyahisi(CAST(:k AS bigint),CAST(NULL AS bigint),CAST(:a AS boolean)) ORDER BY sira_no NULLS LAST,ad",p().addValue("k",k).addValue("a",aktiv),(r,i)->new MehsulQrupu(l(r,"mehsul_qrupu_id"),l(r,"qrup_novu_id"),s(r,"kod"),s(r,"ad"),s(r,"aciqlama"),b(r,"xesteye_cixis_edile_biler"),b(r,"sifarisde_gorunsun"),b(r,"xeste_material_cixisinda_gorunsun"),b(r,"cihaza_cixis_edile_biler"),b(r,"aktiv")));}
    public Map<String,Object> qrupYaddaSaxla(boolean yeni,Long k,Long id,Long nov,String kod,String ad,String ac,boolean xeste,boolean sifaris,boolean material,boolean cihaz,boolean aktiv,Long personal){String sql=yeni?"SELECT * FROM public.fn_mehsul_qrupu_yarat(CAST(:k AS bigint),CAST(:n AS bigint),:kod,:ad,:ac,:x,:s,:m,:c,CAST(:p AS bigint))":"SELECT * FROM public.fn_mehsul_qrupu_yenile(CAST(:id AS bigint),CAST(:k AS bigint),CAST(:n AS bigint),:kod,:ad,:ac,true,:x,:s,:m,:c,:a,CAST(:p AS bigint))";return one(sql,p().addValue("id",id).addValue("k",k).addValue("n",nov).addValue("kod",kod.trim()).addValue("ad",ad.trim()).addValue("ac",n(ac)).addValue("x",xeste).addValue("s",sifaris).addValue("m",material).addValue("c",cihaz).addValue("a",aktiv).addValue("p",personal));}

    public List<Material> materiallar(Long k,Long qrup,Boolean aktiv,String axtaris){return jdbc.query("SELECT * FROM public.fn_material_siyahisi(CAST(:k AS bigint),CAST(:q AS bigint),CAST(:a AS boolean),:x) ORDER BY sira_no NULLS LAST,ad",p().addValue("k",k).addValue("q",qrup).addValue("a",aktiv).addValue("x",n(axtaris)),(r,i)->new Material(l(r,"material_id"),l(r,"qrup_id"),s(r,"qrup_kodu"),s(r,"qrup_adi"),l(r,"vahid_id"),s(r,"vahid_adi"),s(r,"ad"),s(r,"qisa_ad"),s(r,"barkod_nomresi"),d(r,"minimum_miqdar"),d(r,"maksimum_miqdar"),d(r,"stok_boleni"),d(r,"stok_vurma_emsali"),d(r,"stok_bolme_emsali"),b(r,"mehv_edile_biler"),b(r,"paketden_kenar"),b(r,"aktiv"),s(r,"farmasevtik_melumat"),s(r,"istifade_qaydasi"),d(r,"minimum_doza"),d(r,"maksimum_doza"),in(r,"xeste_ucun_maksimum_teleb_muddeti"),d(r,"xeste_ucun_maksimum_teleb_miqdari"),in(r,"yas_asagi_heddi"),in(r,"yas_yuxari_heddi"),d(r,"beden_cekisi"),b(r,"avtomatik_hekim_tesdiqi_olmasin")));}
    public Map<String,Object> materialYaddaSaxla(boolean yeni,Long id,Long k,Long q,Long v,String ad,String qisa,String barkod,java.math.BigDecimal min,java.math.BigDecimal max,boolean mehv,boolean paket,boolean aktiv,String farm,String istifade,Long personal){var p=p().addValue("id",id).addValue("k",k).addValue("q",q).addValue("v",v).addValue("ad",ad.trim()).addValue("qa",n(qisa)).addValue("b",n(barkod)).addValue("min",min).addValue("max",max).addValue("mehv",mehv).addValue("paket",paket).addValue("a",aktiv).addValue("farm",n(farm)).addValue("ist",n(istifade)).addValue("p",personal);String sql=yeni?"SELECT * FROM public.fn_material_yarat(CAST(:k AS bigint),CAST(:q AS bigint),CAST(:v AS bigint),:ad,:qa,:b,CAST(:min AS numeric),CAST(:max AS numeric),NULL,NULL,NULL,:mehv,:paket,:farm,:ist,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,CAST(:p AS bigint))":"SELECT * FROM public.fn_material_yenile(CAST(:id AS bigint),CAST(:k AS bigint),CAST(:q AS bigint),CAST(:v AS bigint),:ad,:qa,true,:b,true,CAST(:min AS numeric),true,CAST(:max AS numeric),true,NULL,true,NULL,true,NULL,true,:mehv,:paket,:a,true,:farm,:ist,NULL,NULL,NULL,NULL,NULL,NULL,NULL,false,CAST(:p AS bigint))";return one(sql,p);}

    public List<EmeliyyatKateqoriyasi> kateqoriyalar(String istiqamet){return jdbc.query("SELECT * FROM public.fn_anbar_emeliyyat_kateqoriya_siyahisi(:i) ORDER BY sira_no NULLS LAST,ad",p().addValue("i",istiqamet),(r,i)->new EmeliyyatKateqoriyasi(l(r,"kateqoriya_id"),s(r,"kod"),s(r,"ad"),s(r,"istiqamet"),s(r,"aciqlama"),in(r,"sira_no"),b(r,"aktiv")));}
    public List<EmeliyyatNovu> emeliyyatlar(Long k,String istiqamet,Boolean aktiv){return jdbc.query("SELECT * FROM public.fn_anbar_emeliyyat_novu_siyahisi(CAST(:k AS bigint),:i,CAST(:a AS boolean)) ORDER BY sira_no NULLS LAST,ad",p().addValue("k",k).addValue("i",istiqamet).addValue("a",aktiv),(r,i)->new EmeliyyatNovu(l(r,"emeliyyat_novu_id"),l(r,"kateqoriya_id"),s(r,"kateqoriya_kodu"),s(r,"kateqoriya_adi"),s(r,"istiqamet"),s(r,"kod"),s(r,"ad"),b(r,"standartdir"),s(r,"aciqlama"),in(r,"sira_no"),b(r,"aktiv")));}
    public Map<String,Object> emeliyyatYaddaSaxla(boolean yeni,Long id,Long k,Long kat,String kod,String ad,boolean standart,String ac,boolean aktiv,Long personal){String sql=yeni?"SELECT * FROM public.fn_anbar_emeliyyat_novu_yarat(CAST(:k AS bigint),CAST(:kat AS bigint),:kod,:ad,:s,:ac,CAST(:p AS bigint))":"SELECT * FROM public.fn_anbar_emeliyyat_novu_yenile(CAST(:id AS bigint),CAST(:k AS bigint),CAST(:kat AS bigint),:kod,:ad,:s,:ac,true,:a,CAST(:p AS bigint))";return one(sql,p().addValue("id",id).addValue("k",k).addValue("kat",kat).addValue("kod",kod.trim()).addValue("ad",ad.trim()).addValue("s",standart).addValue("ac",n(ac)).addValue("a",aktiv).addValue("p",personal));}

    public List<AnbarNovu> anbarNovleri(){return jdbc.query("SELECT * FROM public.fn_anbar_novu_siyahisi() ORDER BY sira_no NULLS LAST,ad",(r,i)->new AnbarNovu(l(r,"anbar_novu_id"),s(r,"kod"),s(r,"ad"),s(r,"aciqlama"),in(r,"sira_no"),b(r,"aktiv")));}
    public List<Anbar> anbarlar(Long k,Long nov,Boolean aktiv,String axtaris){return jdbc.query("SELECT * FROM public.fn_anbar_siyahisi(CAST(:k AS bigint),CAST(:n AS bigint),CAST(:a AS boolean),:x) ORDER BY sira_no NULLS LAST,ad",p().addValue("k",k).addValue("n",nov).addValue("a",aktiv).addValue("x",n(axtaris)),(r,i)->new Anbar(l(r,"anbar_id"),l(r,"anbar_novu_id"),s(r,"anbar_novu_kodu"),s(r,"anbar_novu_adi"),s(r,"kod"),s(r,"ad"),s(r,"aciqlama"),b(r,"teleb_anbaridir"),b(r,"telebde_stok_gorunsun"),b(r,"derman_paketi_tetbiq_edilsin"),b(r,"istehsal_cixisi_edile_biler"),b(r,"mehv_cixisi_edile_biler"),in(r,"cixis_gun_sayi"),in(r,"geriye_mualice_gun_sayi"),date(r,"kilid_baslama_tarixi"),date(r,"kilid_bitme_tarixi"),s(r,"kros_anbar_kodu"),in(r,"sira_no"),b(r,"aktiv")));}
    public Map<String,Object> anbarYaddaSaxla(boolean yeni,Long id,Long k,Long nov,String kod,String ad,String ac,boolean teleb,boolean stok,boolean paket,boolean istehsal,boolean mehv,boolean aktiv,Long personal){String sql=yeni?"SELECT * FROM public.fn_anbar_yarat(CAST(:k AS bigint),CAST(:n AS bigint),:kod,:ad,:ac,:t,:s,:pak,:i,:m,NULL,NULL,CAST(NULL AS timestamp),CAST(NULL AS timestamp),NULL,CAST(:p AS bigint))":"SELECT * FROM public.fn_anbar_yenile(CAST(:id AS bigint),CAST(:k AS bigint),CAST(:n AS bigint),:kod,:ad,:ac,true,:t,:s,:pak,:i,:m,NULL,false,NULL,false,CAST(NULL AS timestamp),false,CAST(NULL AS timestamp),false,NULL,false,:a,CAST(:p AS bigint))";return one(sql,p().addValue("id",id).addValue("k",k).addValue("n",nov).addValue("kod",kod.trim()).addValue("ad",ad.trim()).addValue("ac",n(ac)).addValue("t",teleb).addValue("s",stok).addValue("pak",paket).addValue("i",istehsal).addValue("m",mehv).addValue("a",aktiv).addValue("p",personal));}

    private static String s(ResultSet r,String c)throws SQLException{return r.getString(c);} private static Long l(ResultSet r,String c)throws SQLException{Object o=r.getObject(c);return o instanceof Number x?x.longValue():null;} private static Integer in(ResultSet r,String c)throws SQLException{Object o=r.getObject(c);return o instanceof Number x?x.intValue():null;} private static java.math.BigDecimal d(ResultSet r,String c)throws SQLException{return r.getBigDecimal(c);} private static Boolean b(ResultSet r,String c)throws SQLException{return r.getObject(c,Boolean.class);} private static java.time.LocalDateTime dt(ResultSet r,String c)throws SQLException{return r.getObject(c,java.time.LocalDateTime.class);} private static java.time.LocalDate date(ResultSet r,String c)throws SQLException{var value=dt(r,c);return value==null?null:value.toLocalDate();}
}
