-- DB-dən gələn hazır Parametrlər və Personal menyu adları üçün AZ/EN/RU tərcümələri.
WITH data(dil_kodu,acar,deyer) AS (VALUES
('az','menu.module.mis_param','Parametrlər'),
('en','menu.module.mis_param','Parameters'),
('ru','menu.module.mis_param','Параметры'),
('az','menu.module.mis_personal','Personal idarəetmə'),
('en','menu.module.mis_personal','Personnel management'),
('ru','menu.module.mis_personal','Управление персоналом'),
('az','menu.module.app_service_groups','Xidmət qrupları'),
('en','menu.module.app_service_groups','Service groups'),
('ru','menu.module.app_service_groups','Группы услуг'),
('az','menu.module.app_prices','Xidmət qiymətləri'),
('en','menu.module.app_prices','Service prices'),
('ru','menu.module.app_prices','Цены на услуги'),
('az','menu.module.app_account_codes','Mühasibat kodları'),
('en','menu.module.app_account_codes','Accounting codes'),
('ru','menu.module.app_account_codes','Бухгалтерские коды'),
('az','menu.module.app_department_services','Şöbə xidmətləri'),
('en','menu.module.app_department_services','Department services'),
('ru','menu.module.app_department_services','Услуги отделений'),
('az','menu.module.app_positions','Vəzifələr'),
('en','menu.module.app_positions','Positions'),
('ru','menu.module.app_positions','Должности'),
('az','menu.module.app_buildings','Binalar'),
('en','menu.module.app_buildings','Buildings'),
('ru','menu.module.app_buildings','Здания'),
('az','menu.module.app_building_params','Ümumi parametrlər'),
('en','menu.module.app_building_params','General parameters'),
('ru','menu.module.app_building_params','Общие параметры'),
('az','menu.module.app_beds','Yataqlar'),
('en','menu.module.app_beds','Beds'),
('ru','menu.module.app_beds','Койки'),
('az','menu.module.app_cash_registers','Kassalar'),
('en','menu.module.app_cash_registers','Cash registers'),
('ru','menu.module.app_cash_registers','Кассы'),
('az','menu.module.app_diagnoses','Diaqnozlar'),
('en','menu.module.app_diagnoses','Diagnoses'),
('ru','menu.module.app_diagnoses','Диагнозы'),
('az','menu.module.app_packages','Paketlər'),
('en','menu.module.app_packages','Packages'),
('ru','menu.module.app_packages','Пакеты'),
('az','menu.module.app_roles','Rollar və səlahiyyətlər'),
('en','menu.module.app_roles','Roles and permissions'),
('ru','menu.module.app_roles','Роли и разрешения'),
('az','menu.module.app_modules','Modulların idarə edilməsi'),
('en','menu.module.app_modules','Module management'),
('ru','menu.module.app_modules','Управление модулями'),
('az','menu.module.app_translations','Tərcümələr'),
('en','menu.module.app_translations','Translations'),
('ru','menu.module.app_translations','Переводы')
)
INSERT INTO public.kn_interfeys_tercumeleri(dil_id,acar,deyer)
SELECT d.id,data.acar,data.deyer
FROM data JOIN public.kn_diller d ON d.kod=data.dil_kodu
ON CONFLICT(dil_id,acar) DO UPDATE
SET deyer=EXCLUDED.deyer,yenilenme_tarixi=now();
