CREATE TABLE IF NOT EXISTS public.rn_route_selahiyyetleri (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route varchar(250) NOT NULL,
    http_metod varchar(10) NOT NULL,
    selahiyyet_kodu varchar(100) NOT NULL REFERENCES public.rn_selahiyyetler(kod),
    aktiv boolean NOT NULL DEFAULT true,
    UNIQUE(route,http_metod)
);

CREATE TABLE IF NOT EXISTS public.rn_tehlukesizlik_auditi (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personal_id bigint NULL REFERENCES public.rn_personallar(id),
    istifadeci_adi varchar(150),
    klinika_id bigint,
    hadise_kodu varchar(50) NOT NULL,
    route varchar(500),
    http_metod varchar(10),
    ip_unvan varchar(64),
    ugurlu boolean NOT NULL,
    yaranma_tarixi timestamp NOT NULL DEFAULT current_timestamp
);
CREATE INDEX IF NOT EXISTS ix_tehlukesizlik_auditi_personal_tarix
    ON public.rn_tehlukesizlik_auditi(personal_id,yaranma_tarixi DESC);

INSERT INTO public.rn_route_selahiyyetleri(route,http_metod,selahiyyet_kodu) VALUES
('/xidmetQiymetleri/basliq/yeni','POST','QIYMET_YARAT'),
('/xidmetQiymetleri/qrup/yeni','POST','QIYMET_YARAT'),
('/xidmetQiymetleri/qrup/yenile','POST','QIYMET_YENILE'),
('/xidmetQiymetleri/qiymet','POST','QIYMET_YENILE'),
('/xidmetQiymetleri/qiymetler','POST','QIYMET_YENILE'),
('/rollar/yeni','POST','ROL_IDARE_ET'),
('/rollar/yenile','POST','ROL_IDARE_ET'),
('/rollar/sil','POST','ROL_IDARE_ET'),
('/rollar/icazeler','POST','ROL_IDARE_ET'),
('/emekdash/yeni','POST','PERSONAL_IDARE_ET'),
('/emekdash/yenile','POST','PERSONAL_IDARE_ET'),
('/emekdash/rol','POST','PERSONAL_IDARE_ET')
ON CONFLICT(route,http_metod) DO UPDATE SET selahiyyet_kodu=EXCLUDED.selahiyyet_kodu,aktiv=true;
