UPDATE public.rn_modullar
SET menyuda_gorunsun=false
WHERE aktiv AND route IS NULL AND kod IN (
 'HIS_BILL_INVOICE','HIS_MONTHLY_REPORT','HIS_GEN_WARE_OPE','HIS_DET_WARE_OPE','HIS_PAT_PRESEN',
 'LIS_SETTINGS_ANALYSIS','LIS_SETTINGS_DEVICE','LIS_SETTINGS_BARCODE','LIS_SETTINGS_MIK_BIO'
);
